{
  "openapi": "3.0.0",
  "info": {
    "title": "Atlas API",
    "description": "Documentation of Atlas API",
    "version": "1.0.0"
  },
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "summary": "Create User",
        "description": "Create new User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                },
                "required": ["name", "email"]
              },
              "example": {
                "name": "John Doe",
                "email": "johndoe@test.com"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "fafcab17-627e-48ca-801b-38b678df4763",
                  "admin": false,
                  "name": "John Doe",
                  "email": "jd@test.com",
                  "created_at": "2022-01-15T17:09:36.676Z",
                  "updated_at": "2022-01-15T17:09:36.676Z"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",

            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "Email Already in use."
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users"],
        "summary": "List users",
        "description": "Get all users",
        "parameters": [
          {
            "description": "User id infoe",
            "name": "user_id",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List all users",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Permission danied",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "Not found": {
                    "value": {
                      "error": "User not found."
                    }
                  },
                  "Not admin": {
                    "value": {
                      "error": "Permission denied."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/users/{user_id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Show User",
        "description": "View User informations",
        "parameters": [
          {
            "name": "user_id",
            "description": "User id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "fafcab17-627e-48ca-801b-38b678df4763",
                  "admin": true,
                  "name": "John Doe",
                  "email": "jd@test.com",
                  "created_at": "2022-01-15T17:09:36.676Z",
                  "updated_at": "2022-01-15T17:09:36.676Z"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User not found"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["Users"],
        "summary": "Turn admin",
        "description": "Turn user an admin",
        "parameters": [
          {
            "name": "user_id",
            "description": "User id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "fafcab17-627e-48ca-801b-38b678df4763",
                  "admin": true,
                  "name": "John Doe",
                  "email": "jd@test.com",
                  "created_at": "2022-01-15T17:09:36.676Z",
                  "updated_at": "2022-01-15T17:09:36.676Z"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User not found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      }
    }
  }
}
